version: '3.7'
services:
    lecture-database:
        image: postgres:13-alpine
        container_name: lecturedatabase
        environment:
            - POSTGRES_PASSWORD=test123
            - POSTGRES_DB=lecture_manager
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/database:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        
    lecture-manager:
        image: ghcr.io/telecooperation/lecture-recording-manager:latest
        container_name: lecturemanager
        depends_on:
            - lecture-database
        ports:
            - 8080:80
        volumes:
            - ./docker/mgr:/data
            - ./docker/appsettings.json:/app/appsettings.json
